CREATE DATABASE PROYECTO_FINAL
GO
USE PROYECTO_FINAL
GO

CREATE TABLE USUARIOS (
IDUSUARIO INT IDENTITY(1,1)PRIMARY KEY ,
USUARIO AS ('USER'+RIGHT('00'+CONVERT(VARCHAR,IDUSUARIO),2)),
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(30),
FECHA_NACIMIENTO DATETIME,
TIPOUSUARIO BIT

)
GO
---PROCEDIMIENTO BUSCAR USUARIOS
CREATE PROC [dbo].[SP_BUSCARUSUARIOS]
@BUSCAR NVARCHAR(20)
AS 
SELECT * FROM USUARIOS
WHERE USUARIO LIKE @BUSCAR + '%'
GO

---PROCEDIMIENTO EDITAR USUARIO
CREATE PROC [dbo].[SP_EDITARUSUARIO]
@IDUSUARIO INT,
@NOMBRE NVARCHAR(30),
@APELLIDO VARCHAR(30),
@FECHA_NACIMIENTO DATETIME,
@TIPOUSUARIO BIT
AS
UPDATE USUARIOS SET NOMBRE = @NOMBRE, APELLIDO=@APELLIDO,FECHA_NACIMIENTO=@FECHA_NACIMIENTO,TIPOUSUARIO=@TIPOUSUARIO
WHERE IDUSUARIO = @IDUSUARIO
GO

--- PROCEDIMIENTO PARA ELIMINAR USUARIO
CREATE  PROC [dbo].[SP_ELIMINARUSUARIO]
@IDUSUARIO INT
AS
DELETE USUARIOS
WHERE IDUSUARIO = @IDUSUARIO
GO
--PROCEDIMIENTO INSERTAR USUARIO
CREATE PROC [dbo].[SP_INSERTARUSUARIO]
@NOMBRE NVARCHAR(30),
@APELLIDO VARCHAR(30),
@FECHA_NACIMIENTO DATETIME,
@TIPOUSUARIO BIT
AS
INSERT INTO USUARIOS VALUES (@NOMBRE,@APELLIDO,@FECHA_NACIMIENTO,@TIPOUSUARIO)
GO

CREATE TABLE VISITANTES(
IDVISITANTE INT IDENTITY(1,1) PRIMARY KEY,
CODIGO AS ('VST'+RIGHT('00'+CONVERT(VARCHAR, IDVISITANTE),2)),
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(30),
CARRERA_ID INT,
CORREO VARCHAR(150),
MOTIVO_VISITA VARCHAR(MAX),
FOTO VARCHAR(MAX),
LUGAR_DESTINO_ID INT,
AULA_ID INT,
HORA_ENTRADA VARCHAR(50),
HORA_SALIDA VARCHAR(50),
STATUS BIT,
)
GO
---PROCEDIMIENTO BUSCAR VISITANTES
CREATE PROC [dbo].[SP_BUSCARVISITANTES]
@BUSCAR NVARCHAR(20)
AS 
SELECT * FROM VISITANTES
WHERE NOMBRE LIKE @BUSCAR + '%'
GO
---PROCEDIMIENTO EDITAR VISITANTE
CREATE PROC [dbo].[SP_EDITARVISITANTE]
@IDVISITANTE INT,
@NOMBRE NVARCHAR(30),
@APELLIDO VARCHAR(30),
@CARRERA_ID INT,
@CORREO VARCHAR(150),
@MOTIVO_VISITA VARCHAR(MAX),
@FOTO VARCHAR(MAX),
@LUGAR_DESTINO_ID INT,
@AULA_ID INT,
@HORA_ENTRADA VARCHAR(50),
@HORA_SALIDA VARCHAR(50),
@STATUS BIT
AS
UPDATE VISITANTES SET NOMBRE = @NOMBRE, APELLIDO=@APELLIDO,CARRERA_ID=@CARRERA_ID,CORREO=@CORREO,MOTIVO_VISITA=@MOTIVO_VISITA,FOTO=@FOTO, LUGAR_DESTINO_ID = @LUGAR_DESTINO_ID,AULA_ID=@AULA_ID ,HORA_ENTRADA=@HORA_ENTRADA,HORA_SALIDA=@HORA_SALIDA,STATUS = @STATUS
WHERE IDVISITANTE = @IDVISITANTE
GO
--- PROCEDIMIENTO PARA ELIMINAR VISITANTE
CREATE  PROC [dbo].[SP_ELIMINARVISITANTE]
@IDVISITANTE INT
AS
DELETE VISITANTES
WHERE IDVISITANTE = @IDVISITANTE
GO

--PROCEDIMIENTO INSERTAR VISITANTE
CREATE PROC [dbo].[SP_INSERTARVISITANTE]
@NOMBRE NVARCHAR(30),
@APELLIDO VARCHAR(30),
@CARRERA_ID INT,
@CORREO VARCHAR(150),
@MOTIVO_VISITA VARCHAR(MAX),
@FOTO VARCHAR(MAX),
@LUGAR_DESTINO_ID INT,
@AULA_ID INT,
@HORA_ENTRADA VARCHAR(50),
@HORA_SALIDA VARCHAR(50),
@STATUS BIT
AS
INSERT INTO VISITANTES VALUES (@NOMBRE,@APELLIDO,@CARRERA_ID,@CORREO,@MOTIVO_VISITA,@FOTO,@LUGAR_DESTINO_ID,@AULA_ID,@HORA_ENTRADA,@HORA_SALIDA,@STATUS)
GO

CREATE TABLE CARRERAS(
IDCARRERA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(30)
)
GO
---PROCEDIMIENTO BUSCAR CARRERAS
CREATE PROC [dbo].[SP_BUSCARCARRERAS]
@BUSCAR NVARCHAR(20)
AS 
SELECT * FROM CARRERAS
WHERE NOMBRE LIKE @BUSCAR + '%'
GO
---PROCEDIMIENTO EDITAR CARRERA
CREATE PROC [dbo].[SP_EDITARCARRERA]
@IDCARRERA INT,
@NOMBRE NVARCHAR(30)
AS
UPDATE CARRERAS SET NOMBRE = @NOMBRE
WHERE IDCARRERA = @IDCARRERA
GO
--- PROCEDIMIENTO PARA ELIMINAR CARRERA
CREATE  PROC [dbo].[SP_ELIMINARCARRERA]
@IDCARRERA INT
AS
DELETE CARRERAS
WHERE IDCARRERA = @IDCARRERA
GO
--PROCEDIMIENTO INSERTAR CARRERA
CREATE PROC [dbo].[SP_INSERTARCARRERA]
@NOMBRE NVARCHAR(30)
AS
INSERT INTO CARRERAS VALUES (@NOMBRE)
GO
CREATE TABLE LUGAR_DESTINO(
IDLUGAR_DESTINO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(30)
)
GO
---PROCEDIMIENTO BUSCAR LUGARES
CREATE PROC [dbo].[SP_BUSCARLUGAR]
@BUSCAR NVARCHAR(20)
AS 
SELECT  * FROM LUGAR_DESTINO
WHERE NOMBRE LIKE @BUSCAR + '%'
GO
---PROCEDIMIENTO EDITAR LUGAR
CREATE PROC [dbo].[SP_EDITARLUGAR]
@IDLUGAR_DESTINO INT,
@NOMBRE VARCHAR(30)
AS
UPDATE LUGAR_DESTINO SET NOMBRE = @NOMBRE
WHERE IDLUGAR_DESTINO = @IDLUGAR_DESTINO
GO
--- PROCEDIMIENTO PARA ELIMINAR LUGAR
CREATE  PROC [dbo].[SP_ELIMINARLUGAR]
@IDLUGAR_DESTINO INT
AS
DELETE LUGAR_DESTINO
WHERE IDLUGAR_DESTINO = @IDLUGAR_DESTINO
GO
--PROCEDIMIENTO INSERTAR LUGAR
CREATE PROC [dbo].[SP_INSERTARLUGAR]
@NOMBRE NVARCHAR(30)
AS
INSERT INTO LUGAR_DESTINO VALUES (@NOMBRE)
GO

CREATE TABLE AULAS(
IDAULA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(30),
ID_EDIFICIO INT
)
GO
---PROCEDIMIENTO BUSCAR AULAS
CREATE PROC [dbo].[SP_BUSCARAULAS]
@ID_EDIFICIO INT
AS 
SELECT  * FROM AULAS
WHERE ID_EDIFICIO =@ID_EDIFICIO
GO
---PROCEDIMIENTO EDITAR AULAS
CREATE PROC [dbo].[SP_EDITARAULAS]
@IDAULA INT,
@NOMBRE VARCHAR(30),
@ID_EDIFICIO INT
AS
UPDATE AULAS SET NOMBRE = @NOMBRE
WHERE IDAULA  = @IDAULA 
GO
--- PROCEDIMIENTO PARA ELIMINAR AULA
CREATE  PROC [dbo].[SP_ELIMINARAULA]
@IDAULA INT
AS
DELETE AULAS
WHERE IDAULA = @IDAULA
GO
--PROCEDIMIENTO INSERTAR AULA
CREATE PROC [dbo].[SP_INSERTARAULA]
@NOMBRE NVARCHAR(30),
@ID_EDIFICIO INT
AS
INSERT INTO AULAS VALUES (@NOMBRE,@ID_EDIFICIO)
GO

INSERT INTO AULAS VALUES ('Aula 01',2)

select * from LUGAR_DESTINO
update VISITANTES set CARRERA_ID = 2 where IDVISITANTE =4


select v.IDVISITANTE,v.Codigo, v.NOMBRE,v.APELLIDO,c.NOMBRE as Carrera,v.CORREO,v.MOTIVO_VISITA,v.FOTO,d.NOMBRE as Edificio, a.NOMBRE as Aula,v.HORA_ENTRADA, v.HORA_SALIDA  from VISITANTES v
inner join CARRERAS c on v.CARRERA_ID = c.IDCARRERA
inner join LUGAR_DESTINO d on v.LUGAR_DESTINO_ID = d.IDLUGAR_DESTINO
inner join Aulas a on v.AULA_ID = a.IDAULA where v.STATUS =1

select a.IDAULA,a.NOMBRE,a.ID_EDIFICIO,d.NOMBRE as Edificio from AULAS a 
inner join LUGAR_DESTINO d on a.ID_EDIFICIO = d.IDLUGAR_DESTINO


select distinct IDVISITANTE , MOTIVO_VISITA from visitantes group by IDVISITANTE,IDVISITANTE order by IDVISITANTE desc